print("                                                                  КАЛЬКУЛЯТОР")
print(" By Cheboy")
a = input("1 Калькулятор на умножение")
b = input("2 Калькулятор на деление")
c = input("3 Калькулятор на вычитание")
d = input("4 Калькулятор на сложение")
print("Если вам нужно 1 введите букву 'a'")
print("Если вам нужно 2 введите букву 'b'")
print("Если вам нужно 3 введите букву 'c'")
print("Если вам нужно 4 введите букву 'd'")
if a =='a': print("                                               КАЛЬКУЛЯТОР")
print("                                                 НА УМНОЖЕНИЕ")
TH =float(input("Введите 1 умножаемое: "))
LJ =float(input("Введите 2 умножаемое: "))
result = TH * LJ
print("умноженное : ", result)
PBJ =input(" ")
if b =='b': print("                                               КАЛЬКУЛЯТОР")
print("                                       НА ДЕЛЕНИЕ")
KI =float(input("Введите Делимое: "))
GU =float(input("Введите Делитель: "))
result = KI / GU
print("Ответ : ", result)
LVB =input(" ")
if c =='c': print("                                               КАЛЬКУЛЯТОР")
print("                                       НА ВЫЧИТАНИЕ")
UH =float(input("Введите уменьшаемое: "))
FL =float(input("Введите вычитаемое: "))
result = UH - FL
print("ответ : ", result)
ASS =input(" ")
if d =='d': print("                                               КАЛЬКУЛЯТОР")
print("                                       НА СЛОЖЕНИЕ")
FO =float(input("Введите 1 слогаемое: "))
GD =float(input("Введите 2 слогаемое: "))
result = FO + GD
print("Сложенное : ", result)
FJO =input(" ")
